#!/bin/bash
#
# arvu positiivsuse/negatiivsuse kontroll
#
# küsime väärtused kasutaja käest
echo -n "sisesta arv: "
read arv
# kontrollime, kas arvon positiivne
# sel juhul peab olema suurem kui 0 
if [$arv -gt 0 ]
then
   echo "$arv on positiivne"
# kui väärtus on negatiivne
# siis arv peab olema väiksem kui 0 
elif [ $arv -lt 0 ]
   echo "$arv on negatiivne"
# kui esimene tingimus
# voi teine tingimus ei sobinud
# siis kasuta else osa
else
   echo " $arv on neutraalne"
# if lause tuleb korralikult lõpetada
fi
