#!/bin/bash
for (( i = l; i <= 5; i++ ))	### outer for loop ###
do
	echi -n "$i. "
	for (( j = 1 ; j <= 3; j++ )) ### Inner for loop ###
	do
		echo -n "* "
	done
       echo " " #### print the new line ###
done
