#!/bin/bash

echo -n "ridade arv" 
read arv
echo -n "tarnide arv" 
read reaso
for (( i = 1; i <= 5; i++ ))	### outer for loop ###
do
	echo -n "$i. "
	for (( j = 1 ; j <= 3; j++ )) ### Inner for loop ###
	do
		echo -n "* "
	done
       echo " " #### print the new line ###
done
